# Generated by Django 2.2.7 on 2019-11-10 12:37

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=100)),
                ('community_desc', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('join_allowed', models.BooleanField(default=False)),
                ('newdt_allowed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roledesc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=140)),
                ('gender', models.CharField(choices=[(polls.models.Gender('Female'), 'Female'), (polls.models.Gender('Male'), 'Male')], max_length=1)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='thumbpath')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserRoles')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type_name', models.CharField(max_length=100)),
                ('data_type_desc', models.CharField(default='', max_length=200)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Community')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Community_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_desc', models.CharField(max_length=100)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Community')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.CreateModel(
            name='Communit_Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Community')),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
