# Generated by Django 2.2.7 on 2019-12-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityfollower',
            unique_together={('community', 'follower')},
        ),
    ]
