# Generated by Django 2.2.7 on 2019-11-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191110_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type',
            name='data_type_desc',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Form_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('IM', 'Image'), ('VI', 'Video'), ('AU', 'Audio'), ('TE', 'Text field'), ('TA', 'Text area'), ('UR', 'URI'), ('LO', 'Location'), ('DA', 'Date'), ('DE', 'Decimal'), ('IM', 'Integer')], default='TE', max_length=2)),
                ('field_label', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Community')),
            ],
        ),
        migrations.AddField(
            model_name='data_type',
            name='fields',
            field=models.ManyToManyField(to='polls.Form_Field'),
        ),
    ]
