# Generated by Django 2.2.7 on 2019-11-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191110_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='communit_follower',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='User_Builder_Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
