# Generated by Django 2.2.7 on 2019-11-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191110_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communit_Follower',
            new_name='Community_Follower',
        ),
    ]
