# Generated by Django 2.2.7 on 2019-11-17 13:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_datatype_formfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='formfields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
