# Generated by Django 2.2.7 on 2019-12-07 10:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20191124_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_desc', models.TextField(default='')),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('post_data', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Community')),
                ('data_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.DataType')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
